// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type AnswerResp struct {
	Base   Base   `json:"base"`
	Answer string `json:"answer"`
}

type Base struct {
	Code      int32  `json:"code"`
	Message   string `json:"message"`
	Timestamp int64  `json:"timestamp"`
}

type QuestionReq struct {
	Question string `json:"question"`
}
