// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	test "iterative_control/internal/handler/test"
	"iterative_control/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/question",
				Handler: test.QuestionHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)
}
